"""Generate the diacritic-folding table used by publication search.

Maps precomposed letters whose canonical decomposition is a base letter
followed only by nonspacing marks (category Mn) to that base letter, for the
Latin, Greek, Cyrillic, Arabic and Hebrew presentation-form ranges below. Kana,
Hangul and Indic scripts are excluded because their marks distinguish words.
A few letters with strokes, which have no decomposition, are folded explicitly.
"""
from pathlib import Path
import unicodedata

RANGES = [
    (0x00C0, 0x024F),  # Latin-1 Supplement, Latin Extended-A/B
    (0x0370, 0x03FF),  # Greek and Coptic
    (0x0400, 0x052F),  # Cyrillic and supplement
    (0x0600, 0x06FF),  # Arabic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
    (0x1F00, 0x1FFF),  # Greek Extended
    (0x2C60, 0x2C7F),  # Latin Extended-C
    (0xA720, 0xA7FF),  # Latin Extended-D
    (0xFB1D, 0xFB4F),  # Hebrew presentation forms
]
EXTRA = {"Ø": "O", "ø": "o", "Đ": "D", "đ": "d", "Ł": "L", "ł": "l",
         "Ħ": "H", "ħ": "h", "Ŧ": "T", "ŧ": "t"}

pairs = {}
for start, end in RANGES:
    for code in range(start, end + 1):
        char = chr(code)
        decomposed = unicodedata.normalize("NFD", char)
        if len(decomposed) < 2 or decomposed[0] == char:
            continue
        if all(unicodedata.category(mark) == "Mn" for mark in decomposed[1:]):
            pairs[code] = ord(decomposed[0])
for source, target in EXTRA.items():
    pairs[ord(source)] = ord(target)

values = []
for source in sorted(pairs):
    values.append(f"0x{source:04x}, 0x{pairs[source]:04x},")
lines = ["  " + " ".join(values[i:i + 5]) for i in range(0, len(values), 5)]
output = Path(__file__).resolve().parents[1] / "lib/src/search/folding_table.dart"
output.write_text(
    "// Generated by tool/generate_search_folding.py from Unicode "
    f"{unicodedata.unidata_version} data.\n"
    "// Derived from the Unicode Character Database, (c) Unicode, Inc., under the\n"
    "// Unicode License v3; see ATTRIBUTION.md. Do not edit by hand.\n\n"
    "/// Pairs of code points: a precomposed letter, then its folded base letter.\n"
    "// dart format off\n"
    "const foldingPairs = <int>[\n" + "\n".join(lines) + "\n];\n"
    "// dart format on\n"
)
print(f"Wrote {len(pairs)} mappings (Unicode {unicodedata.unidata_version}) to {output}")
